/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SigninRouteImport } from './routes/signin'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LunaRouteImport } from './routes/luna'
import { Route as GrowthRouteImport } from './routes/growth'
import { Route as GardenRouteImport } from './routes/garden'
import { Route as AdminLoginRouteImport } from './routes/admin-login'
import { Route as IndexRouteImport } from './routes/index'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SigninRoute = SigninRouteImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LunaRoute = LunaRouteImport.update({
  id: '/luna',
  path: '/luna',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowthRoute = GrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => rootRouteImport,
} as any)
const GardenRoute = GardenRouteImport.update({
  id: '/garden',
  path: '/garden',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin-login',
  path: '/admin-login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/luna': typeof LunaRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/luna': typeof LunaRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin-login': typeof AdminLoginRoute
  '/garden': typeof GardenRoute
  '/growth': typeof GrowthRoute
  '/luna': typeof LunaRoute
  '/profile': typeof ProfileRoute
  '/signin': typeof SigninRoute
  '/signup': typeof SignupRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin-login'
    | '/garden'
    | '/growth'
    | '/luna'
    | '/profile'
    | '/signin'
    | '/signup'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin-login'
    | '/garden'
    | '/growth'
    | '/luna'
    | '/profile'
    | '/signin'
    | '/signup'
  id:
    | '__root__'
    | '/'
    | '/admin-login'
    | '/garden'
    | '/growth'
    | '/luna'
    | '/profile'
    | '/signin'
    | '/signup'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminLoginRoute: typeof AdminLoginRoute
  GardenRoute: typeof GardenRoute
  GrowthRoute: typeof GrowthRoute
  LunaRoute: typeof LunaRoute
  ProfileRoute: typeof ProfileRoute
  SigninRoute: typeof SigninRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signin': {
      id: '/signin'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof SigninRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/luna': {
      id: '/luna'
      path: '/luna'
      fullPath: '/luna'
      preLoaderRoute: typeof LunaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/growth': {
      id: '/growth'
      path: '/growth'
      fullPath: '/growth'
      preLoaderRoute: typeof GrowthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/garden': {
      id: '/garden'
      path: '/garden'
      fullPath: '/garden'
      preLoaderRoute: typeof GardenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin-login': {
      id: '/admin-login'
      path: '/admin-login'
      fullPath: '/admin-login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminLoginRoute: AdminLoginRoute,
  GardenRoute: GardenRoute,
  GrowthRoute: GrowthRoute,
  LunaRoute: LunaRoute,
  ProfileRoute: ProfileRoute,
  SigninRoute: SigninRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
